/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Telas;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author kevin
 */
public class TelaGestor extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    Color DefaultColor,ClickedColor;
    
    public TelaGestor() {
        initComponents();
        
        DefaultColor = new Color(20,20,49);
        ClickedColor = new Color(250,87,9);
        
        //Set default color to pan on run time
        
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(DefaultColor);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnFuncionarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnClientes1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BtnLivros = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnStock = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnSair = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/lOGO.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 87, 9));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 20, 49));
        jLabel4.setText("Gestor ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-fechar-janela-55.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 50));

        jPanel3.setBackground(new java.awt.Color(20, 20, 49));

        BtnMenu.setBackground(new java.awt.Color(20, 20, 49));
        BtnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnMenuMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(20, 20, 49));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/menu-50.png"))); // NOI18N
        jLabel2.setText("Menu");

        javax.swing.GroupLayout BtnMenuLayout = new javax.swing.GroupLayout(BtnMenu);
        BtnMenu.setLayout(BtnMenuLayout);
        BtnMenuLayout.setHorizontalGroup(
            BtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnMenuLayout.setVerticalGroup(
            BtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnFuncionarios.setBackground(new java.awt.Color(20, 20, 49));
        BtnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnFuncionariosMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/Funcionario-50.png"))); // NOI18N
        jLabel1.setText("Funcionarios");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout BtnFuncionariosLayout = new javax.swing.GroupLayout(BtnFuncionarios);
        BtnFuncionarios.setLayout(BtnFuncionariosLayout);
        BtnFuncionariosLayout.setHorizontalGroup(
            BtnFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnFuncionariosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnFuncionariosLayout.setVerticalGroup(
            BtnFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnFuncionariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        BtnClientes1.setBackground(new java.awt.Color(20, 20, 49));
        BtnClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClientes1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnClientes1MousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/relatório-gráfico-50.png"))); // NOI18N
        jLabel3.setText("Relatorio");

        javax.swing.GroupLayout BtnClientes1Layout = new javax.swing.GroupLayout(BtnClientes1);
        BtnClientes1.setLayout(BtnClientes1Layout);
        BtnClientes1Layout.setHorizontalGroup(
            BtnClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnClientes1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnClientes1Layout.setVerticalGroup(
            BtnClientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnClientes1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        BtnLivros.setBackground(new java.awt.Color(20, 20, 49));
        BtnLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLivrosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnLivrosMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/livro-50.png"))); // NOI18N
        jLabel6.setText("Livros");

        javax.swing.GroupLayout BtnLivrosLayout = new javax.swing.GroupLayout(BtnLivros);
        BtnLivros.setLayout(BtnLivrosLayout);
        BtnLivrosLayout.setHorizontalGroup(
            BtnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLivrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnLivrosLayout.setVerticalGroup(
            BtnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLivrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        BtnStock.setBackground(new java.awt.Color(20, 20, 49));
        BtnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnStockMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnStockMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/stock-50.png"))); // NOI18N
        jLabel7.setText("Stock");

        javax.swing.GroupLayout BtnStockLayout = new javax.swing.GroupLayout(BtnStock);
        BtnStock.setLayout(BtnStockLayout);
        BtnStockLayout.setHorizontalGroup(
            BtnStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnStockLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnStockLayout.setVerticalGroup(
            BtnStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnStockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        BtnSair.setBackground(new java.awt.Color(20, 20, 49));
        BtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnSairMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/sair-50.png"))); // NOI18N
        jLabel8.setText("Sair");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout BtnSairLayout = new javax.swing.GroupLayout(BtnSair);
        BtnSair.setLayout(BtnSairLayout);
        BtnSairLayout.setHorizontalGroup(
            BtnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnSairLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnSairLayout.setVerticalGroup(
            BtnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnSairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BtnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BtnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BtnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 690));

        desktop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/lOGO.jpg"))); // NOI18N

        desktop.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 990, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFuncionariosMousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(ClickedColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(DefaultColor);
    }//GEN-LAST:event_BtnFuncionariosMousePressed

    private void BtnClientes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientes1MousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(ClickedColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(DefaultColor);

    }//GEN-LAST:event_BtnClientes1MousePressed

    private void BtnLivrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLivrosMousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(ClickedColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(DefaultColor);
    }//GEN-LAST:event_BtnLivrosMousePressed

    private void BtnStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnStockMousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(ClickedColor);
        BtnSair.setBackground(DefaultColor);
    }//GEN-LAST:event_BtnStockMousePressed

    private void BtnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSairMousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(DefaultColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(ClickedColor);
    }//GEN-LAST:event_BtnSairMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BtnClientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientes1MouseClicked
        // TODO add your handling code here:
        Relatorio relatorio = new Relatorio();
        desktop.removeAll();
        desktop.add(relatorio).setVisible(true);
    }//GEN-LAST:event_BtnClientes1MouseClicked

    private void BtnLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLivrosMouseClicked
        // TODO add your handling code here:
        TelaCadastroLivro menuAdicionarLivro = new TelaCadastroLivro();
        desktop.removeAll();
        desktop.add(menuAdicionarLivro).setVisible(true);
    }//GEN-LAST:event_BtnLivrosMouseClicked

    private void BtnStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnStockMouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        desktop.removeAll();
        desktop.add(menu).setVisible(true);
    }//GEN-LAST:event_BtnStockMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
         int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        if(resposta == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario();
        desktop.removeAll();
        desktop.add(tela).setVisible(true);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void BtnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuMousePressed
        // TODO add your handling code here:
        BtnMenu.setBackground(ClickedColor);
        BtnFuncionarios.setBackground(DefaultColor);
        BtnClientes1.setBackground(DefaultColor);
        BtnLivros.setBackground(DefaultColor);
        BtnStock.setBackground(DefaultColor);
        BtnSair.setBackground(DefaultColor);
        
         
    }//GEN-LAST:event_BtnMenuMousePressed

    private void BtnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuMouseClicked
        // TODO add your handling code here:
        MenuHome menuFuncionario = new MenuHome();
        desktop.removeAll();
        desktop.add(menuFuncionario).setVisible(true);
    }//GEN-LAST:event_BtnMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }  catch (ClassNotFoundException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(TelaGestor.class.getName())BtnMenu1va.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnClientes1;
    private javax.swing.JPanel BtnFuncionarios;
    private javax.swing.JPanel BtnLivros;
    private javax.swing.JPanel BtnMenu;
    private javax.swing.JPanel BtnSair;
    private javax.swing.JPanel BtnStock;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
